id: IF6998FEF
ocr_import_info:
  source: bdrc
  software: google_books
  batch: batch_2022
  expected_default_language: bo
  bdrc_scan_id: W4CZ58847
  ocr_info:
    timestamp: 11/17/22T21:15:39
    html: html.zip
    txt: txt.zip
    images: images.zip
  op_import_options: {}
  op_import_version: 0.11.9
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2024-03-05 01:41:39.567235+00:00
last_modified: 2024-03-05 01:41:39.567241+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W4CZ58847
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW4CZ58847
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཤེན་གྱི་བསྟན་རྩིས་རྣམ་དག་ལས་རྩིས་བདར་སྣང་སྲིད་གཏན་འབེབས།
  languages:
  - bo
statistics:
  ocr_word_mean_confidence_index: 0.5058490566037736
  ocr_word_median_confidence_index: 0.49
bases:
  I4CZ75513:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4CZ75513
      total_pages: 55
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4CZ75513.txt
    statistics:
      ocr_word_median_confidence_index: 0.49
      ocr_word_mean_confidence_index: 0.5058490566037736
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
